
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-217-251-77.compute-1.amazonaws.com:5432/d445j33h3fl7u6
    username: chjefmrntzbcma
    password: f1fa1e5b8e02c0f8394eec866279d6c18ae44ca1bb72c9e43a2d338f5c08fff6


  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true





